import { createApp } from "vue";
import ElementPlus from "element-plus";
import "element-plus/dist/index.css";
import router from "./router";
import store from "./store";
import App from "./App.vue";
import "@/styles/index.scss";
const app = createApp(App);
app.use(router).use(store).use(ElementPlus);
app.mount("#app");
