declare const state: {
    allFormList: any[];
    curControl: any;
    currentIndex: number;
    preview: boolean;
    previewShow: boolean;
    save: boolean;
    saveTimetemp: number;
    formUpdate: boolean;
    AllFormResult: any[];
    formResult: Record<string, any>;
    globalDatas: Record<string, any>;
};
export { state };
declare const _default: {
    updateAllFormList(allFormList: any): void;
    setHistory(): void;
    setFormCurrentIndex(index: any): void;
    getGridCurCtrol(item: any, id: string): undefined;
    setPreviewShow(type: any): void;
    handleDynamicForm(): void;
    openPreview(preview: any): void;
    setSave(type: any): void;
    setFormUpdate(type: any): void;
    getControlItems(): any;
    getAllFormList(): any[];
    set(name: any, value: any): void;
    get(name: any): any;
};
export default _default;
