declare const state: {
    allFormList: any[];
    curControl: any;
    currentId: string;
    currentIndex: number;
    preview: boolean;
    previewShow: boolean;
    save: boolean;
    saveTimetemp: number;
    formUpdate: boolean;
    AllFormResult: any[];
    formResult: Record<string, any>;
    globalDatas: Record<string, any>;
};
export { state };
declare const _default: {
    updateAllFormList(allFormList: any): void;
    setHistory(): void;
    setFormCurrentIndex(index: number): void;
    setFormCurrentId(id: string): void;
    getCurrentItem(id: string): undefined;
    getLayoutCurCtrol(item: any, id: string): undefined;
    setPreviewShow(type: any): void;
    handleDynamicForm(): void;
    openPreview(preview: any): void;
    setSave(type: any): void;
    setFormUpdate(type: any): void;
    getControlItems(): any;
    getAllFormList(): any[];
    setAllFormList(item: any): void;
    set(name: any, value: any): void;
    get(name: any): any;
};
export default _default;
